import 'package:ecommerce_ui/models/products.dart';

class MyProducts {
  static List<Products> allProducts = [
    Products(
      id: 1,
      name: "CAMON-30-Pro",
      category: "CAMON",
      image: "assets/images/CAMON-30-Pro-5G-Alps-Snowy-Silver.jpg",
      description: "CAMON-30-Pro-5G-Alps-Snowy-Silver",
      price: 300,
      quantity: 12,
    ),
    Products(
      id: 2,
      name: "CAMON-30-Pro",
      category: "CAMON",
      image: "assets/images/CAMON-30-Pro-5G-Iceland-Basaltic-Dark.jpg",
      description: "CAMON-30-Pro-5G-Alps-Snowy-Silver",
      price: 300,
      quantity: 10,
    ),
    Products(
      id: 3,
      name: "CAMON-30-Pro",
      category: "CAMON",
      image: "assets/images/CAMON-30-Pro-5G-loewe.jpg",
      description: "CAMON-30-Pro-5G-Alps-Snowy-Silver",
      price: 300,
      quantity: 12,
    ),
    Products(
      id: 4,
      name: "Infinix-GT-20",
      category: "Infinix",
      image: "assets/images/Infinix-GT-20-PRO-Mecha-Blue.jpg",
      description: "Infinix-GT-20-PRO-Mecha-Blue",
      price: 250,
      quantity: 20,
    ),
    Products(
      id: 5,
      name: "Infinix-GT-20",
      category: "Infinix",
      image: "assets/images/Infinix-GT-20-PRO-Mecha-Orange.jpg",
      description: "Infinix-GT-20-PRO-Mecha-Orange",
      price: 250,
      quantity: 12,
    ),
    Products(
      id: 6,
      name: "Infinix-GT-20",
      category: "Infinix",
      image: "assets/images/Infinix-GT-20-PRO-Mecha-Silver.jpg",
      description: "Infinix-GT-20-PRO-Mecha-Silver",
      price: 300,
      quantity: 12,
    ),
    Products(
      id: 7,
      name: "iphone-15-pro-max",
      category: "iphone",
      image: "assets/images/iphone-15-pro-max-blacktitanium.jpg",
      description: "iphone-15-pro-max-blacktitanium",
      price: 1200,
      quantity: 20,
    ),
    Products(
      id: 8,
      name: "iphone-15-pro-max",
      category: "iphone",
      image: "assets/images/iphone-15-pro-max-bluetitanium.jpg",
      description: "iphone-15-pro-max-blacktitanium",
      price: 1200,
      quantity: 10,
    ),
    Products(
      id: 9,
      name: "iphone-15-pro-max",
      category: "iphone",
      image: "assets/images/iphone-15-pro-max-naturaltitanium.jpg",
      description: "iphone-15-pro-max-blacktitanium",
      price: 1200,
      quantity: 23,
    ),
    Products(
      id: 10,
      name: "iphone-15-pro-max",
      category: "iphone",
      image: "assets/images/iphone-15-pro-max-whitetitanium.jpg",
      description: "iphone-15-pro-max-blacktitanium",
      price: 1200,
      quantity: 25,
    ),
  ];
  static List<Products> CAMON = [
    Products(
      id: 1,
      name: "CAMON-30-Pro",
      category: "CAMON",
      image: "assets/images/CAMON-30-Pro-5G-Alps-Snowy-Silver.jpg",
      description: "CAMON-30-Pro-5G-Alps-Snowy-Silver",
      price: 300,
      quantity: 12,
    ),
    Products(
      id: 2,
      name: "CAMON-30-Pro",
      category: "CAMON",
      image: "assets/images/CAMON-30-Pro-5G-Iceland-Basaltic-Dark.jpg",
      description: "CAMON-30-Pro-5G-Alps-Snowy-Silver",
      price: 300,
      quantity: 10,
    ),
    Products(
      id: 3,
      name: "CAMON-30-Pro",
      category: "CAMON",
      image: "assets/images/CAMON-30-Pro-5G-loewe.jpg",
      description: "CAMON-30-Pro-5G-Alps-Snowy-Silver",
      price: 300,
      quantity: 12,
    ),
  ];
  static List<Products> Infinix = [
    Products(
      id: 1,
      name: "Infinix-GT-20",
      category: "Infinix",
      image: "assets/images/Infinix-GT-20-PRO-Mecha-Blue.jpg",
      description: "Infinix-GT-20-PRO-Mecha-Blue",
      price: 250,
      quantity: 20,
    ),
    Products(
      id: 2,
      name: "Infinix-GT-20",
      category: "Infinix",
      image: "assets/images/Infinix-GT-20-PRO-Mecha-Orange.jpg",
      description: "Infinix-GT-20-PRO-Mecha-Orange",
      price: 250,
      quantity: 12,
    ),
    Products(
      id: 3,
      name: "Infinix-GT-20",
      category: "Infinix",
      image: "assets/images/Infinix-GT-20-PRO-Mecha-Silver.jpg",
      description: "Infinix-GT-20-PRO-Mecha-Silver",
      price: 300,
      quantity: 12,
    ),

  ];
  static List<Products> iphone = [
    Products(
      id: 1,
      name: "iphone-15-pro-max",
      category: "iphone",
      image: "assets/images/iphone-15-pro-max-blacktitanium.jpg",
      description: "iphone-15-pro-max-blacktitanium",
      price: 1200,
      quantity: 20,
    ),
    Products(
      id: 2,
      name: "iphone-15-pro-max",
      category: "iphone",
      image: "assets/images/iphone-15-pro-max-bluetitanium.jpg",
      description: "iphone-15-pro-max-blacktitanium",
      price: 1200,
      quantity: 10,
    ),
    Products(
      id: 3,
      name: "iphone-15-pro-max",
      category: "iphone",
      image: "assets/images/iphone-15-pro-max-naturaltitanium.jpg",
      description: "iphone-15-pro-max-blacktitanium",
      price: 1200,
      quantity: 23,
    ),
    Products(
      id: 4,
      name: "iphone-15-pro-max",
      category: "iphone",
      image: "assets/images/iphone-15-pro-max-whitetitanium.jpg",
      description: "iphone-15-pro-max-blacktitanium",
      price: 1200,
      quantity: 25,
    ),
  ];
}
